CUDA_PATH	  = /usr/local/apps/cuda/cuda-10.1
CUDA_BIN_PATH = /usr/local/apps/cuda/cuda-10.1/bin
CUDA_NVCC     = /usr/local/apps/cuda/cuda-10.1/bin/nvcc

# arrayMul: arrayMul.cu $(CUDA_NVCC) -o arrayMul arrayMul.cu
arrayMul: arrayMul.cu
	/usr/local/apps/cuda/cuda-10.1/bin/nvcc -o arrayMul arrayMul.cu

